---
################################################################################
#
# Title:        04-1-configure-eth-interface.yml
# Author:       Haseeb Niazi, Shailendra Mruthunjaya, Ulrich Kleidon
# Date:         2020-03-31
# Description:  Configure Ethernet Interfaces with i.e. speed or mtu
#
# Variables:    all_interfaces = List of all interfaces to be configured
#
# Modules:      nxos_interfaces
#
# URLs:         https://galaxy.ansible.com/cisco/nxos
#               https://developer.cisco.com/
#
# Built-in help:
# ansible-doc cisco.nxos.nxos_interfaces
#
################################################################################
#
#- hosts: nexus* 
#  connection: network_cli
#  gather_facts: no
#  tasks:
    - name: 04 Configure network interfaces as layer2 or layer3
      nxos_interfaces:
        config:
          - name: "{{ item.member }}"
            mode: "{{ item.layer | default(default_layer) }}"
            description: "{{ item.description | default(omit) }}"
            speed: "{{ item.speed | default(omit) }}"
            mtu: "{{ item.mtu | default(omit) }}"
            duplex: "{{ item.duplex | default(omit) }}"
            enabled: "{{ item.enabled | default(default_enabled) }}"
        state: "{{ nx_cfg_state }}"
      loop: "{{ all_interfaces }}"
      loop_control:
        label: "{{ item.member }}, Mode: {{ item.layer| default(default_layer) }}"

    - name: 04 Configure FEC mode for 25/50/100G ports
      nxos_config:
        lines: 
          - int {{item.member}} 
          - fec {{ item.fec | default(default_fec) }}
          - spanning-tree port type {{ item.st_port_type | default(default_stpt) }}
      when: item.fec is defined
      loop: "{{ all_interfaces }}"
      loop_control:
        label: "{{ item.member }}, Fec_Mode: {{ item.fec| default(default_fec) }}"
