---
################################################################################
#
# Title:        13-2-configure-vlans-on-n5k_int.yml
# Author:       Haseeb Niazi, Shailendra Mruthunjaya, Ulrich Kleidon
# Date:         2020-03-31
# Description:  Configure VLANs on trunk ports - Nexus 5000 series devices
#
# Variables:    
#
#               
# Modules:      
#
# URLs:         https://galaxy.ansible.com/cisco/nxos
#               https://developer.cisco.com/
#
# Built-in help:
# ansible-doc cisco.nxos.
#
################################################################################
#
#
#- hosts: n5k*
#  connection: network_cli
#  gather_facts: no
#  tasks:
  # This task configues the VLANs on the trunk ports
    - name: 13-2 Configure VLANS on stand-alone trunk ports
      nxos_config:
        lines:
          - switchport trunk native vlan {{ native_vlan_id }}
          - switchport trunk allowed vlan add {{ item.vlans }}
        parents: interface {{ item.member }}
      loop: "{{ trunk_interface_list }}"
      when: trunk_interface_list is defined
      loop_control:
          label: "Interface: {{ item.member }}, VLANs: {{ native_vlan_id + ',' + item.vlans }}"

  # This task configues the VLANs on the trunk ports
    - name: 13-2 Remove VLANS from ports and port-channels
      nxos_config:
        lines:
          - switchport trunk allowed vlan remove {{ item.vlans }}
        parents: interface {{ item.member }}
      loop: "{{ trunk_interface_list }}"
      when: trunk_interface_list is defined and nx_state == 'disabled'
      loop_control:
          label: "PC: {{ item.member }}, VLANs: {{ item.vlans }}"
