---
################################################################################
#
# Title:        17-config-vpc-on-pc.yml
# Author:       Haseeb Niazi, Shailendra Mruthunjaya, Ulrich Kleidon
# Date:         2020-03-31
# Description:  Configure PC participation in VPC
#
# Variables:    mgmt_pool_name = Name of the Management IP pool
#
#               ucs_org = Name of the Sub-Oganization
# Modules:      nxos_
#
# URLs:         https://galaxy.ansible.com/cisco/nxos
#               https://developer.cisco.com/
#
# Built-in help:
# ansible-doc cisco.nxos.
#
################################################################################
#
#
#- hosts: nexus*
#  connection: network_cli
#  gather_facts: no
#  tasks:
   - name: 17 Enabling vPC on all port-channels except peer-link
     nxos_vpc_interface:
       portchannel: "{{ item.id }}"
       vpc: "{{ item.id }}"
       state: "{{ state |default(def_state) }}"
     when: item.id  != peerlink_PC[0].id
     loop: "{{ all_port_channels }}"
     loop_control:
       label: "PC: {{ item.interface }}, VPC ID: {{ item.id }}"



